vbIvod temp ble
Idvon/Pogodnik pull request #1
Opened 2023-02-21 21:37 UTC by Idvon

2023-02-21 21:38 UTC, Idvon commented
Желаю Дмитро победы!

2023-02-21 23:43 UTC, Ledarium commented on PoGoDnIk.py
> +print("Temperature: "+str(data["main"]["temp"])+" C"+"\N{DEGREE SIGN}")
Предлагаю почитать про f-строки и другие методы форматирования, чтобы не городить такую историю с кавычками и плюсами https://shultais.education/blog/python-f-strings. Также полезно при формировании url для реквестов

2023-02-21 23:49 UTC, Ledarium commented on PoGoDnIk.py
> +print("Temperature: "+str(data["main"]["temp"])+" C"+"\N{DEGREE SIGN}")
Не выводится влажность и ветер. Не соответствует ТЗ, уносите

2023-02-21 23:54 UTC, Ledarium commented on PoGoDnIk.py
> +print("Temperature: "+str(data["main"]["temp"])+" C"+"\N{DEGREE SIGN}")
```
╰─ cat config.json
{
"city_name": "Yerevan"
}

╰─ python3 PoGoDnIk.py
Traceback (most recent call last):
  File "/home/dmaylarov/bin/Pogodnik/PoGoDnIk.py", line 10, in <module>
    city_data = city_data[0]
IndexError: list index out of range
```
Если город не нашелся на стороне сервиса, выводится ошибка. Нужно ее обработать

2023-02-21 23:57 UTC, Ledarium requested changes
Не выводится влажность и ветер. Не соответствует ТЗ, уносите

2023-02-23 15:12 UTC, Idvon commented
Please check last commit, my master.

2023-02-23 15:16 UTC, Ledarium requested changes

2023-02-23 15:16 UTC, Ledarium commented on PoGoDnIk.py
> +call = requests.get(f"https://api.openweathermap.org/data/2.5/weather?"
здесь тоже

2023-02-23 15:16 UTC, Ledarium commented on PoGoDnIk.py
>  city_data = city_data[0]
все еще ошибка 
```
╰─ python3 PoGoDnIk.py
Traceback (most recent call last):
  File "/home/dmaylarov/bin/Pogodnik/PoGoDnIk.py", line 10, in <module>
    city_data = city_data[0]
IndexError: list index out of range

╰─ cat config.json
{
"city_name": "afsdfawer"
}
```

2023-02-23 15:49 UTC, Ledarium commented on PoGoDnIk.py
> +print(f"Weather in {city['city_name']}\n"
Добавить вывод информации о стране и штате найденного города

2023-02-23 16:30 UTC, Ledarium approved these changes

2023-02-23 16:30 UTC, merged